---
title: "Youth Risk Behavior Surveillance"
output: html_document
slug: proj2
image_preview: "project2.png"
---

<script src="Youth Risk Behavior Surveillance_files/header-attrs/header-attrs.js"></script>


<p>Every two years, the Centers for Disease Control and Prevention conduct the <a href="https://www.cdc.gov/healthyyouth/data/yrbs/index.htm">Youth Risk Behavior Surveillance System (YRBSS)</a> survey, where it takes data from high schoolers (9th through 12th grade), to analyze health patterns. You will work with a selected group of variables from a random sample of observations during one of the years the YRBSS was conducted.</p>
<div id="load-the-data" class="section level2">
<h2>Load the data</h2>
<p>This data is part of the <code>openintro</code> textbook and we can load and inspect it. There are observations on 13 different variables, some categorical and some numerical. The meaning of each variable can be found by bringing up the help file:</p>
<p>?yrbss</p>
<pre class="r"><code>data(yrbss)
glimpse(yrbss)</code></pre>
<pre><code>## Rows: 13,583
## Columns: 13
## $ age                      &lt;int&gt; 14, 14, 15, 15, 15, 15, 15, 14, 15, 15, 15, 1~
## $ gender                   &lt;chr&gt; &quot;female&quot;, &quot;female&quot;, &quot;female&quot;, &quot;female&quot;, &quot;fema~
## $ grade                    &lt;chr&gt; &quot;9&quot;, &quot;9&quot;, &quot;9&quot;, &quot;9&quot;, &quot;9&quot;, &quot;9&quot;, &quot;9&quot;, &quot;9&quot;, &quot;9&quot;, ~
## $ hispanic                 &lt;chr&gt; &quot;not&quot;, &quot;not&quot;, &quot;hispanic&quot;, &quot;not&quot;, &quot;not&quot;, &quot;not&quot;~
## $ race                     &lt;chr&gt; &quot;Black or African American&quot;, &quot;Black or Africa~
## $ height                   &lt;dbl&gt; NA, NA, 1.73, 1.60, 1.50, 1.57, 1.65, 1.88, 1~
## $ weight                   &lt;dbl&gt; NA, NA, 84.4, 55.8, 46.7, 67.1, 131.5, 71.2, ~
## $ helmet_12m               &lt;chr&gt; &quot;never&quot;, &quot;never&quot;, &quot;never&quot;, &quot;never&quot;, &quot;did not ~
## $ text_while_driving_30d   &lt;chr&gt; &quot;0&quot;, NA, &quot;30&quot;, &quot;0&quot;, &quot;did not drive&quot;, &quot;did not~
## $ physically_active_7d     &lt;int&gt; 4, 2, 7, 0, 2, 1, 4, 4, 5, 0, 0, 0, 4, 7, 7, ~
## $ hours_tv_per_school_day  &lt;chr&gt; &quot;5+&quot;, &quot;5+&quot;, &quot;5+&quot;, &quot;2&quot;, &quot;3&quot;, &quot;5+&quot;, &quot;5+&quot;, &quot;5+&quot;,~
## $ strength_training_7d     &lt;int&gt; 0, 0, 0, 0, 1, 0, 2, 0, 3, 0, 3, 0, 0, 7, 7, ~
## $ school_night_hours_sleep &lt;chr&gt; &quot;8&quot;, &quot;6&quot;, &quot;&lt;5&quot;, &quot;6&quot;, &quot;9&quot;, &quot;8&quot;, &quot;9&quot;, &quot;6&quot;, &quot;&lt;5&quot;~</code></pre>
<p>Before you carry on with your analysis, it’s is always a good idea to check with <code>skimr::skim()</code> to get a feel for missing values, summary statistics of numerical variables, and a very rough histogram.</p>
</div>
<div id="exploratory-data-analysis" class="section level2">
<h2>Exploratory Data Analysis</h2>
<p>You will first start with analyzing the <code>weight</code> of participants in kilograms. Using visualization and summary statistics, describe the distribution of weights. How many observations are we missing weights from?</p>
<pre class="r"><code>skimr::skim(yrbss)</code></pre>
<table>
<caption>(#tab:eda_on_weight)Data summary</caption>
<tbody>
<tr class="odd">
<td align="left">Name</td>
<td align="left">yrbss</td>
</tr>
<tr class="even">
<td align="left">Number of rows</td>
<td align="left">13583</td>
</tr>
<tr class="odd">
<td align="left">Number of columns</td>
<td align="left">13</td>
</tr>
<tr class="even">
<td align="left">_______________________</td>
<td align="left"></td>
</tr>
<tr class="odd">
<td align="left">Column type frequency:</td>
<td align="left"></td>
</tr>
<tr class="even">
<td align="left">character</td>
<td align="left">8</td>
</tr>
<tr class="odd">
<td align="left">numeric</td>
<td align="left">5</td>
</tr>
<tr class="even">
<td align="left">________________________</td>
<td align="left"></td>
</tr>
<tr class="odd">
<td align="left">Group variables</td>
<td align="left">None</td>
</tr>
</tbody>
</table>
<p><strong>Variable type: character</strong></p>
<table>
<thead>
<tr class="header">
<th align="left">skim_variable</th>
<th align="right">n_missing</th>
<th align="right">complete_rate</th>
<th align="right">min</th>
<th align="right">max</th>
<th align="right">empty</th>
<th align="right">n_unique</th>
<th align="right">whitespace</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">gender</td>
<td align="right">12</td>
<td align="right">1.00</td>
<td align="right">4</td>
<td align="right">6</td>
<td align="right">0</td>
<td align="right">2</td>
<td align="right">0</td>
</tr>
<tr class="even">
<td align="left">grade</td>
<td align="right">79</td>
<td align="right">0.99</td>
<td align="right">1</td>
<td align="right">5</td>
<td align="right">0</td>
<td align="right">5</td>
<td align="right">0</td>
</tr>
<tr class="odd">
<td align="left">hispanic</td>
<td align="right">231</td>
<td align="right">0.98</td>
<td align="right">3</td>
<td align="right">8</td>
<td align="right">0</td>
<td align="right">2</td>
<td align="right">0</td>
</tr>
<tr class="even">
<td align="left">race</td>
<td align="right">2805</td>
<td align="right">0.79</td>
<td align="right">5</td>
<td align="right">41</td>
<td align="right">0</td>
<td align="right">5</td>
<td align="right">0</td>
</tr>
<tr class="odd">
<td align="left">helmet_12m</td>
<td align="right">311</td>
<td align="right">0.98</td>
<td align="right">5</td>
<td align="right">12</td>
<td align="right">0</td>
<td align="right">6</td>
<td align="right">0</td>
</tr>
<tr class="even">
<td align="left">text_while_driving_30d</td>
<td align="right">918</td>
<td align="right">0.93</td>
<td align="right">1</td>
<td align="right">13</td>
<td align="right">0</td>
<td align="right">8</td>
<td align="right">0</td>
</tr>
<tr class="odd">
<td align="left">hours_tv_per_school_day</td>
<td align="right">338</td>
<td align="right">0.98</td>
<td align="right">1</td>
<td align="right">12</td>
<td align="right">0</td>
<td align="right">7</td>
<td align="right">0</td>
</tr>
<tr class="even">
<td align="left">school_night_hours_sleep</td>
<td align="right">1248</td>
<td align="right">0.91</td>
<td align="right">1</td>
<td align="right">3</td>
<td align="right">0</td>
<td align="right">7</td>
<td align="right">0</td>
</tr>
</tbody>
</table>
<p><strong>Variable type: numeric</strong></p>
<table>
<thead>
<tr class="header">
<th align="left">skim_variable</th>
<th align="right">n_missing</th>
<th align="right">complete_rate</th>
<th align="right">mean</th>
<th align="right">sd</th>
<th align="right">p0</th>
<th align="right">p25</th>
<th align="right">p50</th>
<th align="right">p75</th>
<th align="right">p100</th>
<th align="left">hist</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">age</td>
<td align="right">77</td>
<td align="right">0.99</td>
<td align="right">16.16</td>
<td align="right">1.26</td>
<td align="right">12.00</td>
<td align="right">15.0</td>
<td align="right">16.00</td>
<td align="right">17.00</td>
<td align="right">18.00</td>
<td align="left">▁▂▅▅▇</td>
</tr>
<tr class="even">
<td align="left">height</td>
<td align="right">1004</td>
<td align="right">0.93</td>
<td align="right">1.69</td>
<td align="right">0.10</td>
<td align="right">1.27</td>
<td align="right">1.6</td>
<td align="right">1.68</td>
<td align="right">1.78</td>
<td align="right">2.11</td>
<td align="left">▁▅▇▃▁</td>
</tr>
<tr class="odd">
<td align="left">weight</td>
<td align="right">1004</td>
<td align="right">0.93</td>
<td align="right">67.91</td>
<td align="right">16.90</td>
<td align="right">29.94</td>
<td align="right">56.2</td>
<td align="right">64.41</td>
<td align="right">76.20</td>
<td align="right">180.99</td>
<td align="left">▆▇▂▁▁</td>
</tr>
<tr class="even">
<td align="left">physically_active_7d</td>
<td align="right">273</td>
<td align="right">0.98</td>
<td align="right">3.90</td>
<td align="right">2.56</td>
<td align="right">0.00</td>
<td align="right">2.0</td>
<td align="right">4.00</td>
<td align="right">7.00</td>
<td align="right">7.00</td>
<td align="left">▆▂▅▃▇</td>
</tr>
<tr class="odd">
<td align="left">strength_training_7d</td>
<td align="right">1176</td>
<td align="right">0.91</td>
<td align="right">2.95</td>
<td align="right">2.58</td>
<td align="right">0.00</td>
<td align="right">0.0</td>
<td align="right">3.00</td>
<td align="right">5.00</td>
<td align="right">7.00</td>
<td align="left">▇▂▅▂▅</td>
</tr>
</tbody>
</table>
<pre class="r"><code>favstats(~weight, data=yrbss)</code></pre>
<pre><code>##   min   Q1 median   Q3 max mean   sd     n missing
##  29.9 56.2   64.4 76.2 181 67.9 16.9 12579    1004</code></pre>
<p><em>There are 1004 missing weights. The average weight is 67.9</em></p>
<pre class="r"><code>ggplot(yrbss, aes (x=weight))+
  geom_boxplot()+
  theme_minimal()+
  NULL</code></pre>
<p><img src="/blogs/Youth%20Risk%20Behavior%20Surveillance_files/figure-html/unnamed-chunk-2-1.png" width="648" style="display: block; margin: auto;" /></p>
<pre class="r"><code>ggplot(yrbss, aes (x=weight))+
  geom_density(alpha = 0.3)+
  theme_minimal()+
  NULL</code></pre>
<p><img src="/blogs/Youth%20Risk%20Behavior%20Surveillance_files/figure-html/unnamed-chunk-2-2.png" width="648" style="display: block; margin: auto;" /></p>
<p><em>Most weight values are reasonable, between 60 and 75. however, there are some outliers, with some children weighting more than 100 and even more than 150</em></p>
<p>Next, consider the possible relationship between a high schooler’s weight and their physical activity. Plotting the data is a useful first step because it helps us quickly visualize trends, identify strong associations, and develop research questions.</p>
<pre class="r"><code>#we first drop all missing values in the dataset
yrbss &lt;- na.omit(yrbss)
#we try to see if there is a correlation between weight and physical activity
yrbss %&gt;% 
  select(physically_active_7d, weight) %&gt;% 
  cor()</code></pre>
<pre><code>##                      physically_active_7d weight
## physically_active_7d               1.0000 0.0403
## weight                             0.0403 1.0000</code></pre>
<p><em>Surprisingly enough, there is no negative correlation. We would’ve expected that the more the physical activity increases, the more weight decreases</em></p>
<pre class="r"><code>weight_by_activity &lt;- yrbss %&gt;% 
  group_by(physically_active_7d) %&gt;% 
  summarise(meanweight= mean(weight)) 
weight_by_activity</code></pre>
<pre><code>## # A tibble: 8 x 2
##   physically_active_7d meanweight
##                  &lt;int&gt;      &lt;dbl&gt;
## 1                    0       67.1
## 2                    1       66.3
## 3                    2       67.8
## 4                    3       68.8
## 5                    4       68.5
## 6                    5       68.3
## 7                    6       68.4
## 8                    7       69.0</code></pre>
<p><em>Indeed, the average eight tends to increase as the level of physical activity increases</em></p>
<pre class="r"><code>plot2&lt;- ggplot(yrbss, aes(x = weight , y = physically_active_7d)) +
  geom_point() + geom_smooth(method = &quot;lm&quot;) 
plot2</code></pre>
<p><img src="/blogs/Youth%20Risk%20Behavior%20Surveillance_files/figure-html/unnamed-chunk-5-1.png" width="648" style="display: block; margin: auto;" /></p>
<p><em>Surprisingly enough, the correlation is positive. Although it is counter intuitive, high weights dont necessarily mean high body fat percentage. Maybe, those who are more physically active have lower body fat but more muscles and therefore wieght more?</em>
Let’s create a new variable in the dataframe <code>yrbss</code>, called <code>physical_3plus</code> , which will be <code>yes</code> if they are physically active for at least 3 days a week, and <code>no</code> otherwise. You may also want to calculate the number and % of those who are and are not active for more than 3 days. RUse the <code>count()</code> function and see if you get the same results as <code>group_by()... summarise()</code></p>
<pre class="r"><code>yrbss &lt;- yrbss %&gt;% 
  mutate(physical_3plus = case_when(
    physically_active_7d &gt;2 ~ &quot;yes&quot;,
    physically_active_7d &lt;2 ~ &quot;no&quot;,
  ))

yrbss %&gt;% 
  count(physical_3plus) %&gt;% 
  mutate(proportions = n/sum(n))</code></pre>
<pre><code>## # A tibble: 3 x 3
##   physical_3plus     n proportions
##   &lt;chr&gt;          &lt;int&gt;       &lt;dbl&gt;
## 1 no              1885      0.226 
## 2 yes             5695      0.682 
## 3 &lt;NA&gt;             771      0.0923</code></pre>
<pre class="r"><code>yrbss %&gt;% 
  group_by(physical_3plus) %&gt;% 
  summarise(n = n()) %&gt;% 
  mutate(proportions = n/sum(n))</code></pre>
<pre><code>## # A tibble: 3 x 3
##   physical_3plus     n proportions
##   &lt;chr&gt;          &lt;int&gt;       &lt;dbl&gt;
## 1 no              1885      0.226 
## 2 yes             5695      0.682 
## 3 &lt;NA&gt;             771      0.0923</code></pre>
<p><em>We get the same results using both functions</em>
Can you provide a 95% confidence interval for the population proportion of high schools that are <em>NOT</em> active 3 or more days per week?</p>
<pre class="r"><code>prop.test(1885,7580)</code></pre>
<pre><code>## 
##  1-sample proportions test with continuity correction
## 
## data:  1885 out of 7580
## X-squared = 1914, df = 1, p-value &lt;2e-16
## alternative hypothesis: true p is not equal to 0.5
## 95 percent confidence interval:
##  0.239 0.259
## sample estimates:
##     p 
## 0.249</code></pre>
<p>Make a boxplot of <code>physical_3plus</code> vs. <code>weight</code>. Is there a relationship between these two variables? What did you expect and why?</p>
<pre class="r"><code>ggplot(yrbss, aes (x=weight, y = physical_3plus))+
  geom_boxplot()+
  theme_minimal()+
  NULL</code></pre>
<p><img src="/blogs/Youth%20Risk%20Behavior%20Surveillance_files/figure-html/boxplot-1.png" width="648" style="display: block; margin: auto;" /></p>
<p><em>As seen before, there is s slight positvie relation between weight and physical activity. We didnt expect this as it is intuitive to say that the most one is physically active the less he/she weights.</em>
## Confidence Interval</p>
<p>Boxplots show how the medians of the two distributions compare, but we can also compare the means of the distributions using either a confidence interval or a hypothesis test. Note that when we calculate the mean, SD, etc. weight in these groups using the mean function, we must ignore any missing values by setting the <code>na.rm = TRUE</code>.</p>
<pre class="r"><code>yrbss %&gt;% 
  group_by(physical_3plus) %&gt;% 
  summarise(n = n(),
            mean_weight = mean(weight, na.rm = TRUE))%&gt;% 
  mutate(se = sd(mean_weight, na.rm = TRUE)/sqrt(n),
         lower = mean_weight - 1.96*se,
         upper = mean_weight + 1.96*se)</code></pre>
<pre><code>## # A tibble: 3 x 6
##   physical_3plus     n mean_weight     se lower upper
##   &lt;chr&gt;          &lt;int&gt;       &lt;dbl&gt;  &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt;
## 1 no              1885        66.9 0.0207  66.8  66.9
## 2 yes             5695        68.7 0.0119  68.7  68.7
## 3 &lt;NA&gt;             771        67.8 0.0324  67.7  67.9</code></pre>
<pre class="r"><code>mosaic::t.test(weight ~ physical_3plus, data = yrbss)</code></pre>
<pre><code>## 
##  Welch Two Sample t-test
## 
## data:  weight by physical_3plus
## t = -4, df = 2963, p-value = 1e-04
## alternative hypothesis: true difference in means between group no and group yes is not equal to 0
## 95 percent confidence interval:
##  -2.724 -0.871
## sample estimates:
##  mean in group no mean in group yes 
##              66.9              68.7</code></pre>
<p>There is an observed difference of about 1.77kg (68.44 - 66.67), and we notice that the two confidence intervals do not overlap. It seems that the difference is at least 95% statistically significant. Let us also conduct a hypothesis test.</p>
</div>
<div id="hypothesis-test-with-formula" class="section level2">
<h2>Hypothesis test with formula</h2>
<p>Write the null and alternative hypotheses for testing whether mean weights are different for those who exercise at least times a week and those who don’t.</p>
<pre class="r"><code>t.test(weight ~ physical_3plus, data = yrbss)</code></pre>
<pre><code>## 
##  Welch Two Sample t-test
## 
## data:  weight by physical_3plus
## t = -4, df = 2963, p-value = 1e-04
## alternative hypothesis: true difference in means between group no and group yes is not equal to 0
## 95 percent confidence interval:
##  -2.724 -0.871
## sample estimates:
##  mean in group no mean in group yes 
##              66.9              68.7</code></pre>
</div>
<div id="hypothesis-test-with-infer" class="section level2">
<h2>Hypothesis test with <code>infer</code></h2>
<p>Next, we will introduce a new function, <code>hypothesize</code>, that falls into the infer workflow. You will use this method for conducting hypothesis tests.</p>
<p>But first, we need to initialize the test, which we will save as <code>obs_diff</code>.</p>
<pre class="r"><code>obs_diff &lt;- yrbss %&gt;%
  specify(weight ~ physical_3plus) %&gt;%
  calculate(stat = &quot;diff in means&quot;, order = c(&quot;yes&quot;, &quot;no&quot;))</code></pre>
<p>Notice how you can use the functions specify and calculate again like you did for calculating confidence intervals. Here, though, the statistic you are searching for is the difference in means, with the order being yes - no != 0.</p>
<p>After you have initialized the test, you need to simulate the test on the null distribution, which we will save as null.</p>
<pre class="r"><code>null_dist &lt;- yrbss %&gt;%
  # specify variables
  specify(weight ~ physical_3plus) %&gt;%
  
  # assume independence, i.e, there is no difference
  hypothesize(null = &quot;independence&quot;) %&gt;%
  
  # generate 1000 reps, of type &quot;permute&quot;
  generate(reps = 1000, type = &quot;permute&quot;) %&gt;%
  
  # calculate statistic of difference, namely &quot;diff in means&quot;
  calculate(stat = &quot;diff in means&quot;, order = c(&quot;yes&quot;, &quot;no&quot;))</code></pre>
<p>Here, <code>hypothesize</code> is used to set the null hypothesis as a test for independence, i.e., that there is no difference between the two population means. In one sample cases, the null argument can be set to <em>point</em> to test a hypothesis relative to a point estimate.</p>
<p>Also, note that the <code>type</code> argument within generate is set to permute, which is the argument when generating a null distribution for a hypothesis test.</p>
<p>We can visualize this null distribution with the following code:</p>
<pre class="r"><code>ggplot(data = null_dist, aes(x = stat)) +
  geom_histogram()</code></pre>
<p><img src="/blogs/Youth%20Risk%20Behavior%20Surveillance_files/figure-html/unnamed-chunk-7-1.png" width="648" style="display: block; margin: auto;" /></p>
<p>Now that the test is initialized and the null distribution formed, we can visualise to see how many of these null permutations have a difference of at least <code>obs_stat</code> of 1.8?</p>
<p>We can also calculate the p-value for your hypothesis test using the function <code>infer::get_p_value()</code>.</p>
<pre class="r"><code>null_dist %&gt;% visualize() +
  shade_p_value(obs_stat = obs_diff, direction = &quot;two-sided&quot;)</code></pre>
<p><img src="/blogs/Youth%20Risk%20Behavior%20Surveillance_files/figure-html/unnamed-chunk-8-1.png" width="648" style="display: block; margin: auto;" /></p>
<pre class="r"><code>null_dist %&gt;%
  get_p_value(obs_stat = obs_diff, direction = &quot;two_sided&quot;)</code></pre>
<pre><code>## # A tibble: 1 x 1
##   p_value
##     &lt;dbl&gt;
## 1       0</code></pre>
</div>
